---
- name: Setup Keycloak server
  hosts: host1
  become: true
  remote_user: root
  gather_facts: yes
  roles:
    - role: docker
      tags: docker
      vars:
        docker_users:
          - apps
        docker_compose_version: "v2.19.1"
    - role: keycloak
      vars:
        domain: "keycloak.test.com"
        acme_account_email: "mostafa.yaghobi@gmail.com"
        hetzner_api_token: "<hetzner_api_token>"
      tags: keycloak
